package roaster

import "math/rand"

// roastTemplates maps each rule to a pool of snarky messages.
var roastTemplates = map[RuleID][]string{
	RuleTooShort: {
		"Ah yes, '%s'. Future you will love this treasure hunt.",
		"'%s'? A commit message so short, it's basically a cry for help.",
		"Even a tweet has more character than this. Literally.",
		"Bold move, writing a commit message shorter than your attention span.",
		"'%s' — the literary equivalent of a shrug emoji.",
		"One day you'll read this in git blame and feel nothing. Because there's nothing to feel.",
		"Is your keyboard missing keys? Because '%s' is not a full thought.",
		"I've seen longer variable names than this commit message.",
		"Did you get charged by the letter for this commit?",
		"Ah, '%s'. A minimalist masterpiece. Truly meaningless.",
		"Short, sweet, and entirely useless to everyone.",
		"Was this commit message generated by a confused pigeon?",
		"'%s'. That's it? Really?",
		"You typed '%s' and thought 'Yeah, they'll know exactly what this means'.",
		"Brevity is the soul of wit, but this is just sad.",
	},
	RuleTooVague: {
		"'%s' could mean literally anything. Schrödinger's commit.",
		"If your commit message was a GPS, it would just say 'go somewhere'.",
		"This commit message has less context than a politician's promise.",
		"'%s' — future archaeologists will be baffled by this artifact.",
		"You might as well have written 'I did a thing' and called it a day.",
		"Your commit message is so vague it could be a horoscope.",
		"Ah, the classic '%s'. Perfect for confusing yourself in three months.",
		"Could you be less specific? Actually, don't try. You might break space-time.",
		"'%s' is the developer equivalent of 'stuff n things'.",
		"A mystery novel has fewer plot holes than this commit message.",
		"Thank you for this valuable insight: '%s'. We are all enlightened.",
		"I'm guessing you don't care much for your coworkers.",
		"'%s'. Wow. Such detail. Much context.",
		"Let me consult my crystal ball to figure out what '%s' means.",
		"This tells me absolutely nothing about what you just changed.",
	},
	RuleAllCaps: {
		"We get it, you're excited. Indoor voice, please.",
		"Calm down. The keyboard didn't do anything to you.",
		"CAPS LOCK: cruise control for cool? Not in commit messages.",
		"Your commit message just yelled at the entire git log.",
		"Take a deep breath. Count to ten. Then rewrite this in lowercase.",
		"PLEASE STOP SCREAMING YOUR COMMIT MESSAGES.",
		"Is your Caps Lock key stuck? Blink twice if you need help.",
		"Writing in all caps doesn't make the code compile faster.",
		"LOUD NOISES!",
		"Okay, okay, I heard you! Jeez.",
		"Aggressive commit messages are not a substitute for therapy.",
		"Someone skipped their morning decaf.",
		"I too like to live dangerously and shout at my version control.",
		"Lower. Case. Letters. They exist.",
		"Who hurt you?",
	},
	RuleNoVerb: {
		"What about it? Did it hurt you? What did you DO?",
		"That's a noun, not a commit message. Verbs exist for a reason.",
		"This reads like a word cloud, not a description of changes.",
		"Your commit message is a statement of existence, not an action.",
		"Git commits describe what you DID, not what you're THINKING about.",
		"A sentence needs a verb. Just like a developer needs coffee.",
		"You stated a thing. Did you add it? Remove it? Break it? Smoke it?",
		"Action words, buddy. We need action words.",
		"It's a commit, not a dictionary entry.",
		"I see the subject, where's the predicate?",
		"Did you skip grammar classes or just common sense?",
		"Point to where the verb is in that sentence. Go ahead, I'll wait.",
		"This is like saying \"sandwich\" when someone asks what you did today.",
		"Needs more 'ing' or 'ed'. Actually, just needs a real verb.",
		"We're missing the 'doing' part of this 'doing work' equation.",
	},
	RuleProfanity: {
		"Save the rage for code review, champ.",
		"Your git log is not your therapist.",
		"Commit messages are permanent. HR can see these.",
		"Future you reading this in git blame will be so proud.",
		"Git stores this forever. Just like the internet. Choose wisely.",
		"Language! We're professionals here. Supposedly.",
		"Did you kiss your motherboard with that mouth?",
		"Swearing at the code won't make the bugs go away.",
		"Such colorful language for such a bland bug fix.",
		"I'll let you have a timeout to think about what you just typed.",
		"The compiler doesn't care about your profanity, and neither do I.",
		"Keep it clean, kid. This is a family-friendly repository.",
		"Profanity in commits? So edgy.",
		"I'm putting a swear jar next to your keyboard.",
		"Your frustration is noted, but please, keep it PG-13.",
	},
	RuleWallOfText: {
		"This isn't your diary. That's what PR descriptions are for.",
		"Your commit message has more words than most README files.",
		"TL;DR: You need a TL;DR for your commit message.",
		"A commit message, not a novel. Save the prose for your memoir.",
		"Subject lines should be punchy, not a paragraph. There's a body for that.",
		"I ain't reading all that. I'm happy for you tho. Or sorry that happened.",
		"Wrap it up, Tolstoy.",
		"This subject line is a marathon. I'm already tired.",
		"Next time, try writing a haiku instead of a thesis.",
		"Does this commit come with a table of contents?",
		"Who has the time to read this in `git log --oneline`?",
		"Brevity. Look it up.",
		"If I wanted to read a book, I wouldn't open a terminal.",
		"Save the long story for the campfire.",
		"It's a git commit, not an open letter to the community.",
	},
	RuleTrailingPeriod: {
		"This isn't an essay. Drop the period, Shakespeare.",
		"A period at the end of a subject line? How... formal.",
		"The period adds nothing but passive-aggressive energy.",
		"Ending with a period is the git equivalent of 'Regards.'",
		"Conventional commits don't end with periods. Now you know.",
		"Ooh, punctuated. We've got a grammar stickler over here.",
		"Is that period structural? Will the commit collapse without it?",
		"Save the punctuation for the code block.",
		"Such finality. Such a dramatic end to a commit message.",
		"We don't need full stops in subject lines. We need speed.",
		"Take that period and put it somewhere useful, like a regex.",
		"Periods are for sentences. This is a title.",
		"Too formal. Makes me feel like I'm reading a legal document.",
		"Drop the dot, keep it rolling.",
		"A single period. The ultimate sign of a developer's exasperation.",
	},
	RuleTicketOnly: {
		"Ah yes, '%s'. Because I totally have all your sprint boards memorized.",
		"Jira called, they want their issue key back.",
		"I'm a compiler, not a scrum master. What does '%s' mean?",
		"Did you really just link a ticket and dip?",
		"Context is for the weak, apparently.",
		"I hope that ticket description is better than this commit message.",
		"Ah, the 'let Jira explain it' approach.",
		"Your colleagues love looking up tickets just to see what you changed.",
		"Is your keyboard broken or are you just lazy?",
		"Just '%s'? Wow. The sheer effort.",
	},
	RuleDespair: {
		"A pull request built on hopes and prayers instead of logic. Excellent.",
		"I see we are using 'driven-by-desperation' development today.",
		"Who needs tests when you have blind faith?",
		"Ah, the 'throw everything at the wall and see what sticks' commit.",
		"I can feel your tears through this commit message.",
		"Please step away from the keyboard and get some sleep.",
		"YOLO-ing into production, I see. Bold strategy.",
		"Are you okay? Blink twice if you need a wellness check.",
		"'Hopefully this works'. Famous last words before breaking prod.",
		"I love the smell of desperation in the morning.",
	},
	RuleFileNameOnly: {
		"Yes, that is a file. But what did you do to it? Buy it dinner?",
		"Ah, the copy-pasted `git status` output commit.",
		"Files don't magically change themselves. What did YOU do?",
		"'%s'. Okay, I see the noun. Where's the verb?",
		"Great observation! That is indeed the name of the file.",
		"Did you edit it, delete it, format it, or just stare at it?",
		"I see you're practicing your file path recitations.",
		"A file was touched. History was made. The details remain a mystery.",
		"You listed the file. Half the job is done. Now for the rest?",
		"Thank you for confirming the existence of '%s'.",
	},
	RuleExclamationOverdose: {
		"Multiple exclamation marks. A sure sign of a diseased mind.",
		"I can smell your caffeine jitters through this commit.",
		"Are you okay?! Why are we yelling?!",
		"Calm down!!! The code isn't going anywhere!!!",
		"One exclamation mark is enough. Three is a cry for help.",
		"Such enthusiasm for such mediocre code.",
		"PUNCTUATION OVERLOAD. ABORT.",
		"You seem very excited about whatever you just broke.",
		"Breathe. Just breathe.",
		"Excessive excitement detected. Engaging dampening fields.",
	},
	RuleDefaultMessage: {
		"Couldn't be bothered to type your own message, huh?",
		"Let me guess, you use the default ringtone too.",
		"Ah, the sweet sound of an autogenerated git commit.",
		"Your creativity is truly bounded.",
		"Letting the machine speak for you. A true cyborg.",
		"I love it when you copy and paste. It shows character.",
		"So original. Much thought.",
		"The default message. The developer's white flag.",
		"Did you accidentally hit enter too early?",
		"Why think when the GitHub UI can do it for you?",
	},
}

// GetRoast returns a random roast for the given rule, with the message substituted.
func GetRoast(id RuleID, msg string) string {
	templates, ok := roastTemplates[id]
	if !ok || len(templates) == 0 {
		return "Your commit message needs work."
	}
	tmpl := templates[rand.Intn(len(templates))]
	// Substitute %s with the commit subject (truncated).
	subject := FirstLine(msg)
	if len(subject) > 40 {
		subject = subject[:37] + "..."
	}
	// Simple manual substitution to avoid importing fmt just for this.
	result := ""
	for i := 0; i < len(tmpl); i++ {
		if i+1 < len(tmpl) && tmpl[i] == '%' && tmpl[i+1] == 's' {
			result += subject
			i++ // skip 's'
		} else {
			result += string(tmpl[i])
		}
	}
	return result
}
